WIP 720 debug legal advisory prefilled data
uktrade/licensing pull request #106
Opened 2024-10-22 11:02 UTC by jenriordan

2024-10-22 16:12 UTC, morganmaerees approved these changes

2024-10-22 17:11 UTC, chris-pettinga requested changes
a small question about change vs update

2024-10-22 17:11 UTC, chris-pettinga commented on django_app/core/forms/base_forms.py
> +        if self.request and self.request.method == "GET" and (self.request.GET.get("change") or self.request.GET.get("update")):
Why are we using `update` when `?change` seems to do the exact same thing? I think we discussed it recently but I'm not clear apologies.

2024-10-24 08:19 UTC, jenriordan commented on django_app/core/forms/base_forms.py
> +        if self.request and self.request.method == "GET" and (self.request.GET.get("change") or self.request.GET.get("update")):
The "update" logic for grounds originates [here](https://github.com/uktrade/licensing/blob/main/django_app/apply_for_a_licence/views/views_services.py#L56)
So this PR is effectively tying the logic that was already present together (and plugging a very small gap).

Using change=yes doesn't address the specific issue of the second legal form being pre-populated. It looks like change=yes has separate logic in use for recipients, business, and yourself.

2024-10-24 09:43 UTC, chris-pettinga approved these changes

2024-10-24 09:47 UTC, merged